# Generated by Django 4.2.7 on 2023-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_name', models.CharField(max_length=64)),
                ('curso_comision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_name', models.CharField(max_length=256)),
                ('estudiante_lastname', models.CharField(max_length=256)),
                ('estudiante_email', models.EmailField(blank=True, max_length=254)),
                ('estudiante_dni', models.CharField(max_length=32)),
                ('estudiante_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('estudiante_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor_name', models.CharField(max_length=256)),
                ('profesor_lastname', models.CharField(max_length=256)),
                ('profesor_email', models.EmailField(blank=True, max_length=254)),
                ('profesor_dni', models.CharField(max_length=32)),
                ('profesor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profesor_birth', models.DateField(null=True)),
                ('profesor_profesion', models.CharField(max_length=128)),
                ('profesor_bio', models.TextField(null=True)),
            ],
        ),
    ]
